server:
  port: 8083
spring:
  application:
    name: zuul-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
zuul:
  routes:
    providet.serviceId: Test-provider
    provider.path: /test/**  #匹配指定的路径，资源匹配的路径才会拦截，转发
  ignored-services: "*"
  prefix: /server