server:
  port: 8085
spring:
  http:
    encoding:
      charset: UTF-8
    force: true
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chengfengpiaopiao/FirstSpringCloud.git
          search-paths: /config-repo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka